Adversarial Autoencoder Implementation [WIP]
bystrogenomics/bystro pull request #341
Opened 2023-11-09 02:01 UTC by austinTalbot7241993

This implements an adversarial autoencoder object for ancestry. No unit tests currently or validation that it works. Will do soon

2023-11-09 02:12 UTC, akotlar commented
that was fast!

2023-11-09 02:45 UTC, austinTalbot7241993 commented
There are a bunch implemented online

2023-11-09 05:02 UTC, akotlar commented
fixed some stuff in https://github.com/austinTalbot7241993/bystro/pull/8

2023-11-09 05:02 UTC, akotlar requested changes
See PR'd changes

2023-11-10 05:04 UTC, akotlar commented on python/python/bystro/ancestry/adversarial_autoencoder.py
> +Adversarial autoencoders (AAEs) represent a novel approach to
Very appreciated

2023-11-13 14:05 UTC, akotlar approved these changes

2023-11-13 14:07 UTC, akotlar commented
Passes our new, stricter mypy standards, and has tests demonstrating the proof of concept AAE. Future PR's will improve model performance.

2023-11-13 14:07 UTC, merged