[WIP] Modified projection method
bystrogenomics/bystro pull request #473
Opened 2024-04-24 21:26 UTC by austinTalbot7241993

Improving the domain adapatation module.

2024-04-25 21:05 UTC, akotlar commented on python/python/bystro/covariance/tests/test_positive_definite_average.py
> +def test_pd_mean_karcher():
could we add tests for the other euclidean and Riemann?

2024-04-25 21:07 UTC, akotlar requested changes
Let's add tests for the Riemann and Euclidean matrix means and then this is good to merge

2024-04-25 23:44 UTC, akotlar requested changes
Let's add tests for euclidian and riemann

2024-04-27 01:23 UTC, austinTalbot7241993 commented
Just removed, will add later.

2024-04-27 01:28 UTC, akotlar approved these changes
LGTM!

2024-04-27 01:28 UTC, merged