Add ability to extract gnomad AFs for PRS.
bystrogenomics/bystro pull request #533
Opened 2024-06-18 20:35 UTC by cristinaetrv

Add extraction of gnomad AFs for the 5 superpopulations using query of target dataset annotation in order to enable weighing PRS by gnomad AFs.

2024-06-18 21:36 UTC, akotlar commented on python/python/bystro/prs/preprocess_for_prs.py
> +def _extract_af_and_loci_overlap(score_loci: set, target_dataset_index: str, user: str) -> pd.DataFrame:
user is CachedAuth

2024-06-18 21:37 UTC, akotlar commented on python/python/bystro/prs/preprocess_for_prs.py
> +def _extract_af_and_loci_overlap(score_loci: set, target_dataset_index: str, user: str) -> pd.DataFrame:
and then we want to take an optional opensearch_cluster_config, which is a dict

2024-06-18 21:39 UTC, akotlar commented on python/python/bystro/prs/preprocess_for_prs.py
> +def _extract_af_and_loci_overlap(score_loci: set, target_dataset_index: str, user: str) -> pd.DataFrame:
and both user and opensearch_cluster_config should be optional; we just need to check that one is not None (and has values)

2024-06-18 21:40 UTC, akotlar requested changes
A few small changes then LGTM

2024-06-24 21:13 UTC, cristinaetrv commented
Included in #529

2024-06-24 21:13 UTC, closed without merging